name: PR Build

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Install dependencies for SCA scan
      - name: Install Dependencies
        run: npm install

      # Run Snyk Code Test and save output to file
      - name: Run Snyk Test
        run: snyk test 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Parse vulnerability summary from output
    
