name: PR Build

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Run Snyk Code Test and save output to file
      - name: Run Snyk Code Test
        run: snyk code test > snyk-output.txt || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Parse vulnerability summary from output
      - name: Parse Vulnerability Summary
        run: |
          SUMMARY_LINE=$(grep "Summary:" -A 3 snyk-output.txt | tail -n 1)

          HIGH=$(echo "$SUMMARY_LINE" | awk '{print $1}')
          MEDIUM=$(echo "$SUMMARY_LINE" | awk '{print $3}')
          LOW=$(echo "$SUMMARY_LINE" | awk '{print $5}')

          echo "High vulnerabilities: $HIGH"
          echo "Medium vulnerabilities: $MEDIUM"
          echo "Low vulnerabilities: $LOW"

          if [ "$HIGH" -gt 0 ]; then
            echo "Failing: High vulnerabilities found."
            exit 1
          elif [ "$HIGH" -eq 0 ] && [ "$MEDIUM" -gt 10 ]; then
            echo "Failing: More than 10 medium vulnerabilities found."
            exit 1
          else
            echo "Severity threshold check passed."
          fi
