name: PR Build

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Install dependencies (required for SCA scan)
      - name: Install Dependencies
        run: npm install || true

      # Step 1: Run SAST (Snyk Code Test)
      - name: Run Snyk Code Test
        run: snyk code test > snyk-output.txt || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Show SAST Output
        run: cat snyk-output.txt

      # Step 2: Run SCA (Snyk Open Source Test)
      - name: Run Snyk SCA Test
        run: snyk test > scascan.txt || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Show SCA Output
        run: cat scascan.txt

      # Step 3: Analyse SCA Scan Results
      - name: Analyse SCA Scan Results
        run: |
          if grep -q "\[Critical Severity\]" scascan.txt || grep -q "\[High Severity\]" scascan.txt; then
            echo "Critical or High severity vulnerabilities found in SCA scan."
            echo "SCA_FAIL=true" >> $GITHUB_ENV
          else
            echo "No Critical or High severity vulnerabilities found in SCA scan."
          fi

      # Step 4: Parse SAST Vulnerability Summary 
      - name: Parse SAST Vulnerability Summary
        run: |
          SUMMARY_LINE=$(grep "Summary:" -A 3 snyk-output.txt | tail -n 1 || echo "")

          HIGH=$(echo "$SUMMARY_LINE" | awk '{print $1}')
          MEDIUM=$(echo "$SUMMARY_LINE" | awk '{print $3}')
          LOW=$(echo "$SUMMARY_LINE" | awk '{print $5}')

          echo "High vulnerabilities: $HIGH"
          echo "Medium vulnerabilities: $MEDIUM"
          echo "Low vulnerabilities: $LOW"

          if [ "$HIGH" -gt 0 ]; then
            echo "High vulnerabilities found in SAST."
            echo "SAST_FAIL=true" >> $GITHUB_ENV
          elif [ "$HIGH" -eq 0 ] && [ "$MEDIUM" -gt 10 ]; then
            echo "More than 10 medium vulnerabilities found in SAST."
            echo "SAST_FAIL=true" >> $GITHUB_ENV
          else
            echo "SAST severity threshold check passed."
          fi

      # Step 5: Final Fail Check
      - name: Fail if any scan failed
        run: |
          if [ "${SCA_FAIL}" = "true" ] || [ "${SAST_FAIL}" = "true" ]; then
            echo "Build failed due to vulnerabilities."
            exit 1
          else
            echo "All checks passed."
          fi
