name: Snyk Scan

on:
  push:
    branches: [ main ]

jobs:
  snyk:
    name: Snyk Scan for Node.js
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          command: test

      - name: Monitor project with Snyk
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

      - name: Log in to GitHub Container Registry
        run:  docker login ghcr.io -u anitkurianesec --password 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

      - name: Build and push the Docker image
        run: |
          docker build . --tag ghcr.io/anitkurianesec/snyktest:latest
          docker push ghcr.io/anitkurianesec/snyktest:latest

      - name: Testing for Code Vulnerabilties
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test

      - name: Generating SBOM
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: sbom --format cyclonedx1.4+json --json-file-output mySBOM.json

    



          

     
