name: Snyk Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  snyk:
    name: Snyk Open Source Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@v1
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test

    - name: Monitor project on Snyk
      uses: snyk/actions/node@v1
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor
